### ISSUE TITLE
Password Reset Email Case Sensitivity

### ISSUE THREAD

**Issue by tadscottsmith** [openmhz/trunk-server#143]
Just a heads up that it seems the email address in the password reset function is case sensitive. If you use a different case for the email address than you signed up with, it will respond with **No account register for x@y.com**.

**Comment by robotastic** [comment]
interesting - in general, it looks like things could get messed up because of case sensitivity.... like even for logins.

**Comment by robotastic** [comment]
This should be fixed now - thanks for spotting it!
