### ISSUE TITLE
Spectrogram audio player

### ISSUE THREAD

**Issue by leee** [openmhz/trunk-server#46]
Whenever I fiddle with audio, and it's not something I can visualize directly (e.g. a gnuradio plot sink), then I'll go straight to an audio workstation/editor like Audition or Audacity.

These tools are not only great for audio analyses and mangling for testing, but they're also great for visual playback. Seeing periods of inactivity lets you seek forward to where there's audio activity again, or for visually identifying artificial alert tones - which are remarkably easy to pick out even in FTs of low sampling frequency.

Instead of the barebones audio player that exists right now, I believe having this same visual playback would be a wonderful creature comfort for end users, and one that's possible with this JavaScript library that I saw a few years ago: [`wavesurfer.js`](http://wavesurfer-js.org/example/spectrogram/index.html).

I'd imagine that modifying the player and adding this feature to just the currently chosen/playing audio is easiest, with a toggle for users to enable/disable this feature if the 8-16 kHz audio low resolution FFT is too taxing locally. This also has the benefit of no additional cost to server-side compute.

Maybe spectrograms could be generated for every call in the archive view with the FFT as a background of each call entry or something to that effect - but in order to keep processing local, this would require preloading of audio and that wouldn't be cheap on bandwidth, although it's not a far stretch from the bandwidth consumed from autoplayer-enabled views.

**Comment by robotastic** [comment]
I like this idea - I am actually doing something along these lines for the Twitter Card  player. I am using the wavesurfer.js library for this. I would probably be useful for analog systems where you might have long recordings. Being able to easily click to different portions of the call would be helpful too.

https://twitter.com/DispatchDc/status/1393756076986834946

**Comment by ge0metrix** [comment]
👍 

It'd be great to have a visual of the call for like you said the ability to search to actual audio. 

Also would allow visual identification of tones etc in a call.
